spring:
  datasource:
    url: jdbc:mysql://localhost:3310/Employee?useUnicode=true&characterEncoding=utf-8
    username: wzzheng
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8083